read_globals = {
  AbandonQuest = {},
  AcceptQuest = {},
  BuyTrainerService = {},
  C_GossipInfo = {
    fields = {
      CloseGossip = {},
      GetActiveQuests = {},
      GetAvailableQuests = {},
      GetOptions = {},
      GetText = {},
      SelectActiveQuest = {},
      SelectAvailableQuest = {},
      SelectOption = {},
    },
  },
  C_Timer = {
    fields = {
      After = {},
    },
  },
  CancelLogout = {},
  CloseMerchant = {},
  CloseTrainer = {},
  CompleteQuest = {},
  CreateFrame = {},
  DoEmote = {},
  EnumerateFrames = {},
  EventRegistry = {
    fields = {
      frameEventFrame = {
        fields = {
          HookScript = {},
          RegisterEvent = {},
          UnregisterAllEvents = {},
        },
      },
    },
  },
  ExpandFactionHeader = {},
  GetBinding = {},
  GetFactionInfo = {},
  GetGameMessageInfo = {},
  GetInventoryItemDurability = {},
  GetMerchantItemInfo = {},
  GetMerchantNumItems = {},
  GetNumBindings = {},
  GetNumFactions = {},
  GetNumQuestChoices = {},
  GetNumQuestLogEntries = {},
  GetNumQuestRewards = {},
  GetNumTrainerServices = {},
  GetObjectiveText = {},
  GetPhysicalScreenSize = {},
  GetProgressText = {},
  GetQuestID = {},
  GetQuestItemInfo = {},
  GetQuestLogTitle = {},
  GetQuestReward = {},
  GetQuestText = {},
  GetRaidTargetIndex = {},
  GetRewardMoney = {},
  GetRewardText = {},
  GetRewardXP = {},
  GetSubZoneText = {},
  GetTitleText = {},
  GetTrainerGreetingText = {},
  GetTrainerServiceCost = {},
  GetTrainerServiceInfo = {},
  GetTrainerServiceLevelReq = {},
  GetZoneText = {},
  hooksecurefunc = {},
  Mixin = {},
  ReloadUI = {},
  SelectQuestLogEntry = {},
  SetAbandonQuest = {},
  SetCVar = {},
  seterrorhandler = {},
  SetOverrideBinding = {},
  SetTrainerServiceTypeFilter = {},
  StaticPopup1Text = {},
  table = {
    fields = {
      wipe = {},
    },
  },
  UIParent = {
    fields = {
      RegisterEvent = {},
    },
  },
  UnitGUID = {},
  UnitHealth = {},
  UnitName = {},
  UnitPower = {},
  WorldFrame = {
    fields = {
      ClearAllPoints = {},
      SetHeight = {},
      SetPoint = {},
      SetWidth = {},
    },
  },
}
